services:
  mearn-app:
    container_name: mearn-app
    build:
      context: .
      dockerfile: ./Dockerfile.app.dev
    depends_on:
      mearn-database:
        condition: service_healthy
        restart: true
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore: # by default includes .dockerignores
            - package-lock.json
    environment:
      - NODE_ENV=development

  mearn-database:
    container_name: mearn-database
    build:
      context: .
      dockerfile: ./Dockerfile.db.dev
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - mearn-database-data:/var/lib/postgresql/data
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mearn-app-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 3

volumes:
  mearn-database-data:
    name: "mearn-database-data"
